development:
  adapter: mysql2
  encoding: utf8
  database: my_db_name
  username: root
  password: root

production:
  adapter: mysql2
  encoding: utf8
  database: my_db_name
  username: root
  password: root